CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';

CREATE DATABASE IF NOT EXISTS authentication;
GRANT ALL PRIVILEGES ON authentication.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS user;
GRANT ALL PRIVILEGES ON user.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS product;
GRANT ALL PRIVILEGES ON product.* TO 'user'@'%';

CREATE DATABASE IF NOT EXISTS orders;
GRANT ALL PRIVILEGES ON orders.* TO 'user'@'%';

FLUSH PRIVILEGES;
